### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by mantoni**
I looked through all the changes carefully and couldn't find anything that is semantically breaking for us. I did a Mochify release with streams 3 based on Browserify 13 as well. It would be nice to have the same version of streams everywhere.

Also removed `assert` as it's implicitly added through Browserify.

I think this can go out as a minor.

### CODE REVIEW

**Comment by ferlores** [comment]
LGTM, thanks!

**Comment by ferlores** [comment]
Published as 2.4.1

**Comment by ferlores** [comment]
ups just re-read your comment about publishing as a minor. I did a patch, I still think that we are good. Otherwise I can revert and publish as 2.5

**Comment by mantoni** [comment]
Nah, I think it's fine. Thanks!

**Pull request merged**
