### PR TITLE
Gather coverage from all sources

### PR DESCRIPTION
**Pull request by SteffenL**
This PR should be feature-complete but it needs documentation and tests.

Can you kindly have a look and suggest how to go about writing tests for this? Please let me know if you have other issues with the code.

Added new options that can be set as CLI parameters:

* `include`: One or more glob patterns for file inclusion. Can be used with `exclude` as well.
* `all`: Gather coverage from all files similarly to Istanbul's `--all`/`--include-all-sources` parameter. Non-tested files will show up in the report instead of being absent.
* `root`: Can (only) be used with `all` to specify the root directory of the files to search for to reduce the amount of files to match. A good example might be to set it to `src`. Defaults to the current working directory.

To avoid depending on a new library, I wrote a basic "directory walker" function, which has a guard against entering the same directories repeatedly. All of these files are added to the Browserify pipeline using `b.add()` without any regards to the tested files (that are already picked up for coverage reporting).

### CODE REVIEW

**Comment by SteffenL** [comment]
FYI, the master branch has one failing test on my machine:
```

  Basic
    √ should instrument the code and run report (794ms)
    √ should instrument multiple files and only expose coverage once (636ms)
    √ should collect multiple coverage statistics (654ms)
    √ should report 50% coverage (632ms)
Error: Exit 1

    √ should not fail if test fails (620ms)
    √ should not modify the output of mochify (1245ms)
    √ should not instrument the exclude the pattern (616ms)
    √ should not instrument the exclude the patterns (627ms)
    √ should not fail if no instrumented files (610ms)
    - should support other instrumenters that support ES6
    √ should work with babelify (931ms)
    √ should allow to include files in node_modules folders (619ms)
Error: Exit 1

    1) should print full test reports when run from the command line


  11 passing (10s)
  1 pending
  1 failing

  1) Basic should print full test reports when run from the command line:

      Uncaught AssertionError [ERR_ASSERTION]: cli did not print full test report
      + expected - actual

      -# phantomjs:
      -1..1
      -not ok 1 test1 should fail 50%
      -  AssertionError: This should be true
      -      at fail (node_modules/assert/assert.js:200)
      -      at ok (node_modules/assert/assert.js:215)
      -      at test/fixtures/fail-50.js:9
      -# tests 1
      -# pass 0
      -# fail 1

      at c:\p\mochify-istanbul\test\basic.js:267:16
      at ChildProcess.exithandler (child_process.js:298:5)
      at maybeClose (internal/child_process.js:961:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
```

The other tests are OK even with my changes.

**Comment by mantoni** [comment]
Hmmm, Browserify provides us with all the files that end up in the bundle. I don't really see why I would want files that are in the source directory, but that are never used in the bundle to show up as not covered. The purpose of coverage is to prove that the code in the bundle is covered by the tests. I'd say you could delete the files that do not end up in the bundle because they're not needed. Or am I missing the point?

**Comment by SteffenL** [comment]
If you aim to have as much code coverage as possible, then it would be helpful to know whether you have written tests or not. Otherwise you might think that coverage is great when it is not.

The untested files cannot be deleted because they are probably used in the project, just that they do not have any tests. Maybe the app/library was written before the tests.

I do have a an example where I already had a fairly new project without any tests. I started by writing a single test to get 100% coverage in one source file. This looked great in the report but the real coverage was much lower.

## Example reports
```
mochify --plugin [ mochify-istanbul --report text --include "**/src/**" ]
```
```
-----------|----------|----------|----------|----------|----------------|
File       |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-----------|----------|----------|----------|----------|----------------|
 src\      |      100 |      100 |      100 |      100 |                |
  Util.js  |      100 |      100 |      100 |      100 |                |
-----------|----------|----------|----------|----------|----------------|
All files  |      100 |      100 |      100 |      100 |                |
-----------|----------|----------|----------|----------|----------------|
```
The project has a single test for `Util.js`. This leads me to think that the project has only one source file and that the overall coverage is good. I added an `include` pattern here to exclude files in `test/`, and because I only care about files in `src/`.

```
mochify --plugin [ mochify-istanbul --report text --all --root src --include "**/src/**" ]
```
```
---------------------|----------|----------|----------|----------|----------------|
File                 |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
---------------------|----------|----------|----------|----------|----------------|
 src\                |    18.08 |     0.76 |     2.29 |     18.1 |                |
  Example01.js       |     9.27 |        0 |      0.9 |     9.27 |... 0,1294,1307 |
  Example02.js       |       40 |     7.14 |     9.09 |       40 |... 166,167,169 |
  Example03.js       |    30.43 |        0 |     8.33 |    30.43 |... 319,321,325 |
  Example04.js       |    13.02 |        0 |     2.79 |     13.1 |... 8,2540,2544 |
  Example05.js       |    23.14 |    10.98 |     7.89 |    23.14 |... 765,774,790 |
  Example06.js       |    27.91 |        0 |        0 |    27.91 |... 170,171,173 |
  Example07.js       |    15.56 |        0 |        0 |    15.56 |... 581,582,586 |
  Example08.js       |    23.37 |        0 |        0 |    23.37 |... 2,1385,1387 |
  Example09.js       |     62.5 |    33.33 |       60 |     62.5 |... 57,58,73,77 |
  Example10.js       |    13.64 |        0 |     0.73 |    13.64 |... 4,1335,1337 |
  Example11.js       |    15.05 |        0 |     3.33 |    15.05 |... 318,332,349 |
  Example12.js       |    51.28 |        0 |     7.69 |    51.28 |... 192,206,220 |
  Example13.js       |     9.24 |        0 |        0 |     9.24 |... 1,1885,1889 |
  Example14.js       |    21.59 |        0 |     2.28 |    21.59 |... 5,3998,4001 |
  Example15.js       |    15.96 |        0 |     3.13 |    15.96 |... 290,292,296 |
  Example16.js       |    13.33 |        0 |        0 |    13.33 |... 211,213,217 |
  Example17.js       |    19.89 |        0 |        0 |    19.89 |... 674,694,715 |
  Example18.js       |    21.02 |        0 |     1.32 |    21.02 |... 9,3471,3473 |
  Example19.js       |    10.23 |        0 |     1.28 |    10.23 |... 788,790,794 |
  Example20.js       |    13.77 |        0 |     1.09 |    13.77 |... 970,972,976 |
  Example21.js       |    16.98 |        0 |     9.09 |    16.98 |... 218,220,224 |
  Util.js            |      100 |      100 |      100 |      100 |                |
  Example22.js       |    31.75 |        0 |     9.09 |    32.26 |... 183,185,188 |
  Example23.js       |      100 |      100 |      100 |      100 |                |
  Example24.js       |     17.2 |        0 |     2.56 |     17.2 |... 759,762,775 |
---------------------|----------|----------|----------|----------|----------------|
All files            |    18.08 |     0.76 |     2.29 |     18.1 |                |
---------------------|----------|----------|----------|----------|----------------|
```
The real coverage of the entire `src` directory is not good. I added an `include` pattern here to exclude files in `test/`, and because I only care about files in `src/` (there are used third party files in `lib/`).

**Comment by mantoni** [comment]
Thanks for the illustration. It got me curious and I also ran some tests. You can find it here: https://github.com/mantoni/mochify-istanbul-coverage-test

This illustrates the point I was trying to make. If your bundle does not include a file, it is not part of the coverage statistics. If you incude it, but don't use it, the coverage drops. This behavior is exactly as I want it to be. It makes no sense to me that files that don't end up in the bundle lower the coverage.

**Comment by SteffenL** [comment]
The fact that coverage drops is the exact reason why this (optional) feature is important. Istanbul CLI supports this via `--all` or `--include-all-sources`, so I do not see a good reason why we are not allowed to do the same with `mochify-istanbul`. If you do not need it, then you do not need to use the feature,  while those do need it can.

**Comment by mantoni** [comment]
You get me wrong. This module is specifically for Browserify. Including files in the coverage report that are not Browserified makes no sense. I value your effort, but this feature would produce wrong coverage results. This module measures the coverage of the Browserify bundle, not the coverage of the files in the source tree. Does that make sense?

**Comment by SteffenL** [comment]
Okay, I understand you. Do you suggest that we solve the problem in mochify instead? I believe that my work does add the files in the source tree to the Browserify bundle, but if I understand correctly, you do not want mochify-istanbul to have this responsibility.

**Comment by mantoni** [comment]
I don't see a problem that needs solving 🤔 I'm not sure how I can get my point across. Mochify is a tool to test Browserify bundles. If your code does not include certain files, you're not testing them and they're not needed. You could delete them without breaking anything. Why would you want those files to reduce your coverage? You might even have some utility scripts in the sources or files that are only used when running on node. Why would you want those to interfere with your coverage report? I think adding this solution causes more confusion than solving anything.

If you want to know which source files are not part of your bundle, that could be a separate tool. You could write a Browserify plugin that verifies that all source files actually end up in the bundle. I guess that is what you want, right?

**Comment by SteffenL** [comment]
I will try to explain carefully "from scratch" so that you can get a better idea about whether this is a valid issue or not. Maybe it is not.

You are correct that I want to know which files have coverage and which files do not. I also do not have time to write a lot of plugins and integrations with the different services I use (I would like to move on and work on what I am really supposed to work on).

I want to know about the overall coverage during local development, in the Travis CI build log, and I want a report in a PR on GitHub that shows me the coverage of the whole code base (`src` directory), or at least allows me to look at the report in detail which will show me that files are not covered.

I decided to use Mochify to test my browser-only library in different browsers, because the JS testing framework I planned to use ([Intern](https://theintern.io)) had a blocking bug, and Mochify seems like a good and easy-to-use alternative.

I use Parcel to bundle my library for consumption. This bundle has all of the used files in the `src` directory whether they are tested or not. Mochify is however not testing this bundle, but instead bundles the tested files using Browserify.

My project is set up with GitHub and Codecov integration. When I make PRs on GitHub, the reviewers can always get an idea about the overall coverage and look at the report more closely without digging through the source tree to find untested files.

If the coverage report in the PR is always 100%/unchanging, then perhaps nobody in the team is going to bother spending more time and effort on figuring out the real coverage of the whole code base.

**Comment by SteffenL** [comment]
Maybe I need to think harder about whether I want this feature or not. I can see in another project, there are definitely files that are not tested, and they are not in the coverage report on Codecov. I will need to discuss it with my team, because I am not sure anymore whether my other team members have even considered this before.

Since there are people who requested such a feature in Istanbul, I thought that this feature would definitely be useful (for them).

**Comment by mantoni** [comment]
> I use Parcel to bundle my library for consumption. This bundle has all of the used files in the src directory whether they are tested or not.

Mochify will also have all files that are `require`d from your main entry. It's not about which files you're actually testing. Like my demonstration shows, coverage drops if files are used in the code that are not tested at all.

Anyway, here is a solution that could work for you: Create an entry point that requires all files in your `src` directory (e.g. `all-sources.js` and use `--require all-sources.js` to include it in the Browserify bundle. This makes them all part of the bundle regardless of what the tests files do.

**Comment by SteffenL** [comment]
I have not tested your suggested solution yet but it seems like it should work, although I wanted to avoid having to create another file that recursively `require()`s from the `src/`.

Would you like to keep anything at all from this PR?

Thank you for being patient with me.

**Comment by SteffenL** [comment]
Here is a discussion about the issue I tried to solve:
https://github.com/gotwarlost/istanbul/issues/112

They want files to show with 0% coverage, however, which is what I think I would want as well if the files are not being `require()` anywhere. The feature I added will show untested as having more than 0% coverage simply due to the files being executed.

I am not sure if my work will produce the exact same report as `istanbul cover --include-all-sources [...]`.

**Comment by mantoni** [comment]
Thanks for the link. Interestingly, they closed the issue for the same reason and suggested the same workaround as I did.

**Comment by SteffenL** [comment]
Seems like my work does the exact same thing as `istanbul cover --include-all-sources [...]`, which causes files to look partially covered, as you told me earlier. I can agree that it would be misleading. I still think that the feature would be very good to have if untested files actually show in the report with 0% coverage. I do not know if I can do this, but would you be more interested in that? Perhaps that should be fixed in Istanbul itself instead.

**Comment by mantoni** [comment]
Again, what you refer to as "untested files" are actuall "unused files". I'm not willing to show "unused files" with 0% coverage. Not even behind a flag. "Untested files" already show up in the report. Source files are only concidered if they're in the Browserify bundle. If you want something to show up, make it appear in the bundle. Simple and straight forward. The root cause of your issue seems to be that Parcel and Browserify work differently. Maybe Mochify is not for you. It's specifically build to make Browserify and Mocha play nicely.

**Comment by SteffenL** [comment]
I feel like I am coming off as being difficult, but it is not my intention.


I just believe that regardless of whether it is a "problem" that should be solved by Mochify, mochify-istanbul, Istanbul itself or something else, it is useful for myself and others that reports can be more complete and show source files that are not used by tests, without requiring much extra work from the end user.

Istanbul CLI has this feature already, so they saw a use for it. It is just that it would be more useful for unused files to show 0% coverage instead of appearing to have wrong coverage.

**Comment by SteffenL** [comment]
To clarify, it would be fine for me if all of the files that are in the bundle but not used by tests, show in the report with 0% coverage instead of appearing to have wrong coverage. If files are not in the bundle then it is fine that they do not show up in the report.

Something also has to be responsible for adding those files to the bundle without requiring much extra work from the end-user. Istanbul CLI has this feature already, so they probably saw a use for it. It is just that it would be more useful for unused files to show 0% coverage instead of appearing to have wrong coverage.

Maybe we both feel ready to end this discussion. Even if my work produces the same result as Istanbul CLI's `--include-all-sources`, it is not actually good enough for me. I appreciate that you have listened and shared your thoughts.

**Comment by mantoni** [comment]
Ok. I ran another test. I think you can have what you want already. Just add all `src` files explicitly to the bundle, e.g. with a glob pattern. Like this: `mochify --plugin [ mochify-istanbul --report text ] test/*.js src/*.js`. Let me know if this solves it for you.

**Comment by SteffenL** [comment]
That really does give the same result! In that case, the only extra thing my work has is the include pattern/filter, but it is not really that useful. Thank you!

**Comment by mantoni** [comment]
Ha! Nice that we found a solution without even touching the code. You're welcome.

**Pull request closed without merging**
