### PR TITLE
Collect multiple coverage statistics

### PR DESCRIPTION
**Pull request by Swatinem**
mochify might generate multiple output, such as when running with
multiple webdriver instances

### CODE REVIEW

**Comment by Swatinem** [comment]
Any chance to get this merged? This time I have proper tests and no breakage :-D

**Comment by ferlores** [comment]
Sorry for the delay. Thanks for the update. I'm merging and releasing

**Comment by ferlores** [comment]
v2.3.0 is released

**Comment by Swatinem** [comment]
Thanks :-)

**Pull request merged**
